# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
appVersion: "1.0"
description: A Helm chart for magma metrics
name: metrics
version: 1.4.24
engine: gotpl
sources:
  - https://github.com/magma/magma
keywords:
  - magma
  - orc8r
  - metrics

dependencies:
  - name: victoria-metrics-single
    version: 0.6.18
    repository: "https://victoriametrics.github.io/helm-charts"
    condition: victoriametrics.create
  - name: victoria-metrics-alert
    version: 0.3.21
    repository: "https://victoriametrics.github.io/helm-charts"
    condition: victoriametrics.create
  - name: thanos
    version: 0.3.28
    repository: "@banzaicloud-stable"
    condition: thanos.enabled
